"""
NarrativeEngine — orchestrates LLM narrative generation with three cost levers:

  1. PROMPT CACHING   — system prompt + chart digest cached via Anthropic's
                        cache_control. ~90% cheaper on cached input.
  2. RESPONSE CACHING — same chart + same options → served from disk cache.
                        No LLM call at all on hit.
  3. PARALLEL ASYNC   — all 7 sections run concurrently via asyncio.gather.
                        Same cost, but ~7x faster wall time.

The engine reports per-section token usage so you can verify the savings.
"""

from __future__ import annotations
import asyncio
from dataclasses import dataclass, field
from typing import List, Dict, Optional

from ..core.chart import Chart
from ..core.yogas import Yoga
from ..core.dasha import DashaPeriod
from .digest import build_chart_digest
from .llm_provider import (
    LLMProvider, LLMConfig, LLMResult, default_provider,
)
from .prompts import (
    system_blocks, BRIEFS, SECTION_HEADERS, section_ids,
)
from .cache import NarrativeCache


# Per-language scale factor on max_tokens.
#
# Malayalam Unicode characters consume roughly 2.5–3× the tokens that
# Latin characters do; Latin-script Malayalam (Manglish) sits roughly 1.5×.
# Without scaling, sections truncate mid-paragraph in non-English modes.
# These factors were chosen empirically from the Anthropic tokenizer.
_LANG_TOKEN_SCALE = {
    "english":          1.0,
    "manglish":         1.5,
    "malayalam":        1.5,   # Latin-script transliteration — same as Manglish
    "malayalam_script": 2.5,   # Real Malayalam Unicode — needs the most room
}

def _max_tokens_for(language: str, base: int) -> int:
    """
    Return a per-section token budget scaled for the language.
    Capped at 8192 so we never exceed the model's per-response cap.
    """
    factor = _LANG_TOKEN_SCALE.get(language, 1.0)
    return min(int(base * factor), 8192)


# ---------------------------------------------------------------------------
# Configuration / result dataclasses
# ---------------------------------------------------------------------------

@dataclass
class NarrativeOptions:
    language: str = "english"
    sections: List[str] = field(default_factory=section_ids)
    model: str = "claude-sonnet-4-6"
    temperature: float = 0.55
    max_tokens_per_section: int = 1600
    use_response_cache: bool = True
    parallel: bool = True


@dataclass
class SectionUsage:
    section: str
    input_tokens: int = 0
    output_tokens: int = 0
    cache_creation_tokens: int = 0
    cache_read_tokens: int = 0
    cache_hit: bool = False


@dataclass
class NarrativeUsage:
    """Aggregate telemetry across all sections in one generation run."""
    sections: List[SectionUsage] = field(default_factory=list)
    response_cache_hit: bool = False
    provider: str = ""

    @property
    def total_input(self) -> int:
        return sum(s.input_tokens for s in self.sections)

    @property
    def total_output(self) -> int:
        return sum(s.output_tokens for s in self.sections)

    @property
    def total_cache_read(self) -> int:
        return sum(s.cache_read_tokens for s in self.sections)

    @property
    def total_cache_write(self) -> int:
        return sum(s.cache_creation_tokens for s in self.sections)

    def summary(self) -> str:
        if self.response_cache_hit:
            return "Response cache HIT — no LLM call made."
        n = len(self.sections)
        hits = sum(1 for s in self.sections if s.cache_hit)
        return (
            f"{n} sections generated by {self.provider}.\n"
            f"  Prompt-cache hits   : {hits}/{n}\n"
            f"  Tokens in (uncached): {self.total_input}\n"
            f"  Tokens in (cache rd): {self.total_cache_read}\n"
            f"  Tokens in (cache wr): {self.total_cache_write}\n"
            f"  Tokens out          : {self.total_output}"
        )


@dataclass
class NarrativeResult:
    digest: str
    sections: Dict[str, str]
    options: NarrativeOptions
    provider_name: str
    usage: NarrativeUsage

    def to_markdown(self, include_digest: bool = False) -> str:
        out: List[str] = ["# Janma Kundali — A Room 48 Reading\n"]
        for sec_id in self.options.sections:
            if sec_id not in self.sections:
                continue
            out.append(f"## {SECTION_HEADERS[sec_id]}\n")
            out.append(self.sections[sec_id])
            out.append("")
        if include_digest:
            out.append("\n---\n")
            out.append("## Appendix — Computed Chart Digest (ground truth)\n")
            out.append(self.digest)
        return "\n".join(out)

    def to_dict(self) -> dict:
        """For JSON serialization / response caching."""
        return {
            "digest": self.digest,
            "sections": self.sections,
            "provider_name": self.provider_name,
            "options": {
                "language": self.options.language,
                "sections": self.options.sections,
                "model": self.options.model,
                "temperature": self.options.temperature,
            },
        }


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------

class NarrativeEngine:
    """
    The LLM narrative layer.

    Usage:
        engine = NarrativeEngine()                          # auto-picks provider
        result = engine.generate(chart, yogas, dashas)      # full reading
        print(result.usage.summary())                       # see token savings
    """

    def __init__(self,
                 provider: Optional[LLMProvider] = None,
                 cache: Optional[NarrativeCache] = None):
        self.provider = provider or default_provider()
        self.cache = cache if cache is not None else NarrativeCache()

    # ---- public API -----------------------------------------------------
    def generate(self,
                 chart: Chart,
                 yogas: List[Yoga],
                 dashas: List[DashaPeriod],
                 options: Optional[NarrativeOptions] = None
                 ) -> NarrativeResult:
        """
        Synchronous wrapper. If options.parallel and the provider supports
        async, sections are generated concurrently under the hood.
        """
        opts = options or NarrativeOptions()
        digest = build_chart_digest(chart, yogas, dashas, language=opts.language)

        # 1) Response cache check
        if opts.use_response_cache:
            cache_key = self._response_cache_key(digest, opts)
            cached = self.cache.get(cache_key)
            if cached is not None:
                return NarrativeResult(
                    digest=cached["digest"],
                    sections=cached["sections"],
                    options=opts,
                    provider_name=cached["provider_name"],
                    usage=NarrativeUsage(
                        sections=[], response_cache_hit=True,
                        provider=cached["provider_name"],
                    ),
                )

        # 2) Generate
        if opts.parallel:
            sections, usage = asyncio.run(
                self._generate_parallel(digest, opts))
        else:
            sections, usage = self._generate_sequential(digest, opts)

        result = NarrativeResult(
            digest=digest,
            sections=sections,
            options=opts,
            provider_name=self.provider.name,
            usage=usage,
        )

        # 3) Store to response cache
        if opts.use_response_cache:
            self.cache.put(self._response_cache_key(digest, opts),
                           result.to_dict())

        return result

    # ---- private --------------------------------------------------------
    @staticmethod
    def _response_cache_key(digest: str, opts: NarrativeOptions) -> str:
        return NarrativeCache.make_key(
            digest,
            opts.language,
            opts.model,
            f"{opts.temperature:.3f}",
            ",".join(opts.sections),
        )

    async def _generate_parallel(self, digest, opts):
        """Fire all section calls concurrently."""
        sys_blocks = system_blocks(opts.language, digest)
        config = LLMConfig(
            model=opts.model,
            temperature=opts.temperature,
            max_tokens=_max_tokens_for(opts.language, opts.max_tokens_per_section),
        )
        valid_secs = [s for s in opts.sections if s in BRIEFS]
        briefs = [BRIEFS[s] for s in valid_secs]

        results: list[LLMResult] = await self.provider.generate_many(
            sys_blocks, briefs, config)

        sections: Dict[str, str] = {}
        usage = NarrativeUsage(provider=self.provider.name)
        for sec_id, r in zip(valid_secs, results):
            sections[sec_id] = r.text
            usage.sections.append(SectionUsage(
                section=sec_id,
                input_tokens=r.input_tokens,
                output_tokens=r.output_tokens,
                cache_creation_tokens=r.cache_creation_tokens,
                cache_read_tokens=r.cache_read_tokens,
                cache_hit=r.cache_hit,
            ))
        return sections, usage

    def _generate_sequential(self, digest, opts):
        """Fallback: run section calls one by one."""
        sys_blocks = system_blocks(opts.language, digest)
        config = LLMConfig(
            model=opts.model,
            temperature=opts.temperature,
            max_tokens=_max_tokens_for(opts.language, opts.max_tokens_per_section),
        )
        sections: Dict[str, str] = {}
        usage = NarrativeUsage(provider=self.provider.name)
        for sec_id in opts.sections:
            if sec_id not in BRIEFS:
                continue
            r = self.provider.generate(sys_blocks, BRIEFS[sec_id], config)
            sections[sec_id] = r.text
            usage.sections.append(SectionUsage(
                section=sec_id,
                input_tokens=r.input_tokens,
                output_tokens=r.output_tokens,
                cache_creation_tokens=r.cache_creation_tokens,
                cache_read_tokens=r.cache_read_tokens,
                cache_hit=r.cache_hit,
            ))
        return sections, usage
