"""
FastAPI service for the Kerala Astrology Agent.

Endpoints:
    GET  /                       Service info
    GET  /health                 Health probe
    POST /api/v1/horoscope       Full horoscope (chart + yogas + dashas + interpretation)
    POST /api/v1/chart           Just the Rasi chart
    POST /api/v1/dashas          Just the Vimshottari dasha tree
    POST /api/v1/yogas           Just the detected yogas
    POST /api/v1/report-text     Plain-text human-readable report
    GET  /api/v1/timezone        Resolve timezone from lat/lon

Run with:
    uvicorn kerala_astro.api.main:app --reload --port 8000
Then open:
    http://localhost:8000/docs
"""

from datetime import datetime
from typing import Optional

from fastapi import FastAPI, HTTPException, status, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import PlainTextResponse, JSONResponse
import swisseph as swe
from timezonefinder import TimezoneFinder

from ..core.chart import BirthData, compute_chart
from ..core.dasha import (compute_vimshottari, find_current_dasha,
                          find_current_antardasha)
from ..core.yogas import detect_all_yogas
from ..core.interpret import interpret_antardasha
from ..agent.horoscope_agent import HoroscopeAgent

from .schemas import (
    BirthDataRequest, HoroscopeResponse, ChartResponse, YogaResponse,
    DashaResponse, HealthResponse, ErrorResponse,
    NarrativeRequest, NarrativeResponse, NarrativeSectionResponse,
)
from .converters import (
    chart_to_response, yoga_to_response, dasha_to_response,
    md_to_interpretation,
)


# ---------------------------------------------------------------------------
# App configuration
# ---------------------------------------------------------------------------

API_VERSION = "1.0.0"

app = FastAPI(
    title="Room 48 — Kerala Astrology API",
    description=(
        "Room 48 generates a Kerala-tradition (Parashari) janma kundali from "
        "date, time and place of birth. Uses sidereal Lahiri ayanamsa "
        "and whole-sign houses. Computes Vimshottari dasha, detects classical "
        "yogas (Pancha Mahapurusha, Raja, Dhana, Gajakesari, Kuja dosha, "
        "Kalasarpa, and others), and produces a flowing LLM-narrated reading "
        "grounded strictly in the computed chart facts."
    ),
    version=API_VERSION,
    contact={"name": "Room 48"},
    license_info={"name": "For educational/spiritual use"},
)

# CORS — open by default so it's usable from any frontend. Lock down in prod.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _to_birthdata(req: BirthDataRequest) -> BirthData:
    return BirthData(
        name=req.name,
        year=req.year, month=req.month, day=req.day,
        hour=req.hour, minute=req.minute, second=req.second,
        latitude=req.latitude, longitude=req.longitude,
        timezone_name=req.timezone_name,
        place_name=req.place_name,
    )


def _resolve_tz(birth: BirthData) -> str:
    if birth.timezone_name:
        return birth.timezone_name
    tf = TimezoneFinder()
    tz = tf.timezone_at(lat=birth.latitude, lng=birth.longitude)
    if not tz:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=("Could not determine timezone from coordinates. "
                    "Please supply timezone_name explicitly."))
    return tz


def _safe_compute(birth: BirthData):
    """Wrap chart computation with HTTP-friendly error mapping."""
    try:
        return compute_chart(birth)
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(e))
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Computation error: {e}")


DISCLAIMER = (
    "This reading is generated by Room 48 using classical Kerala/Parashari "
    "rules. It indicates tendencies and karmic themes, not fixed outcomes. "
    "Conscious effort (purushartha) and parihara (remedial measures) can "
    "modify results. For major life decisions, consult a qualified human "
    "astrologer."
)


# ---------------------------------------------------------------------------
# Meta endpoints
# ---------------------------------------------------------------------------

@app.get("/", tags=["meta"])
def root():
    return {
        "service": "Room 48 — Kerala Astrology API",
        "version": API_VERSION,
        "docs": "/docs",
        "openapi": "/openapi.json",
        "endpoints": [
            "POST /api/v1/horoscope",
            "POST /api/v1/chart",
            "POST /api/v1/dashas",
            "POST /api/v1/yogas",
            "POST /api/v1/report-text",
            "POST /api/v1/narrative",
            "GET  /api/v1/timezone",
        ],
    }


@app.get("/health", response_model=HealthResponse, tags=["meta"])
def health():
    # Smoke-test Swiss Ephemeris by calling get_ayanamsa
    swe_ok = False
    try:
        swe.set_sid_mode(swe.SIDM_LAHIRI)
        _ = swe.get_ayanamsa_ut(2451545.0)   # J2000
        swe_ok = True
    except Exception:
        pass
    return HealthResponse(
        status="ok" if swe_ok else "degraded",
        service="room48-kerala-astrology",
        version=API_VERSION,
        swiss_ephemeris=swe_ok,
    )


# ---------------------------------------------------------------------------
# Main horoscope endpoint
# ---------------------------------------------------------------------------

@app.post("/api/v1/horoscope",
          response_model=HoroscopeResponse,
          tags=["horoscope"],
          summary="Full janma kundali",
          responses={422: {"model": ErrorResponse}})
def generate_horoscope(req: BirthDataRequest):
    """
    Computes the complete horoscope:
    chart, yogas, full Vimshottari dasha tree, current dasha interpretation,
    upcoming Mahadasha analyses, and a plain-text report.
    """
    birth = _to_birthdata(req)
    tz_name = _resolve_tz(birth)

    chart = _safe_compute(birth)
    dashas = compute_vimshottari(chart,
                                 include_pratyantar=req.include_pratyantar)
    yogas = detect_all_yogas(chart)

    current_md = find_current_dasha(dashas)
    current_md_interp = None
    current_ad_note = None
    if current_md:
        current_md_interp = md_to_interpretation(chart, current_md)
        ad = find_current_antardasha(current_md)
        if ad:
            current_ad_note = interpret_antardasha(chart, current_md, ad)

    now = datetime.utcnow()
    upcoming = [md for md in dashas if md.start > now][: req.num_upcoming_dashas]
    upcoming_interps = [md_to_interpretation(chart, md) for md in upcoming]

    # Reuse the agent for the prose report
    agent = HoroscopeAgent(include_pratyantar=req.include_pratyantar)
    full_text = agent.generate(birth)["report_text"]

    return HoroscopeResponse(
        chart=chart_to_response(chart, tz_name),
        yogas=[yoga_to_response(y) for y in yogas],
        dashas=[dasha_to_response(d) for d in dashas],
        current_mahadasha=current_md_interp,
        current_antardasha_note=current_ad_note,
        upcoming_mahadashas=upcoming_interps,
        full_text_report=full_text,
        disclaimer=DISCLAIMER,
    )


# ---------------------------------------------------------------------------
# Slice endpoints
# ---------------------------------------------------------------------------

@app.post("/api/v1/chart",
          response_model=ChartResponse,
          tags=["chart"],
          summary="Rasi chart only")
def get_chart(req: BirthDataRequest):
    birth = _to_birthdata(req)
    tz_name = _resolve_tz(birth)
    chart = _safe_compute(birth)
    return chart_to_response(chart, tz_name)


@app.post("/api/v1/dashas",
          response_model=list[DashaResponse],
          tags=["dasha"],
          summary="Vimshottari dasha tree only")
def get_dashas(req: BirthDataRequest):
    birth = _to_birthdata(req)
    chart = _safe_compute(birth)
    dashas = compute_vimshottari(chart,
                                 include_pratyantar=req.include_pratyantar)
    return [dasha_to_response(d) for d in dashas]


@app.post("/api/v1/yogas",
          response_model=list[YogaResponse],
          tags=["yogas"],
          summary="Detected yogas only")
def get_yogas(req: BirthDataRequest):
    birth = _to_birthdata(req)
    chart = _safe_compute(birth)
    yogas = detect_all_yogas(chart)
    return [yoga_to_response(y) for y in yogas]


@app.post("/api/v1/report-text",
          response_class=PlainTextResponse,
          tags=["horoscope"],
          summary="Plain-text horoscope report")
def get_report_text(req: BirthDataRequest):
    """Returns the human-readable text report (the same content the CLI prints)."""
    birth = _to_birthdata(req)
    agent = HoroscopeAgent(include_pratyantar=req.include_pratyantar)
    return agent.generate(birth)["report_text"]


# ---------------------------------------------------------------------------
# Utility endpoint
# ---------------------------------------------------------------------------

@app.get("/api/v1/timezone",
         tags=["utility"],
         summary="Resolve IANA timezone from coordinates")
def resolve_timezone(
    latitude: float = Query(..., ge=-90, le=90),
    longitude: float = Query(..., ge=-180, le=180),
):
    tf = TimezoneFinder()
    tz = tf.timezone_at(lat=latitude, lng=longitude)
    if not tz:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No timezone found for these coordinates.")
    return {"latitude": latitude, "longitude": longitude, "timezone": tz}


# ---------------------------------------------------------------------------
# Narrative (LLM) endpoint
# ---------------------------------------------------------------------------

from ..narrative.engine import NarrativeEngine, NarrativeOptions
from ..narrative.prompts import BRIEFS, SECTION_HEADERS, section_ids as _all_section_ids


@app.post("/api/v1/narrative",
          response_model=NarrativeResponse,
          tags=["narrative"],
          summary="LLM-generated astrological narrative",
          responses={422: {"model": ErrorResponse},
                     503: {"model": ErrorResponse}})
def generate_narrative(req: NarrativeRequest):
    """
    Computes the chart, runs the yoga and dasha engines, then asks an LLM
    to render a flowing astrological reading grounded ONLY in the computed
    facts. The LLM is constrained by a strict system prompt — it never
    invents positions, dates, or yogas.

    Provider is chosen by environment:
      - ANTHROPIC_API_KEY set → AnthropicProvider (real LLM)
      - otherwise            → EchoProvider (no network calls, for tests)
    """
    birth = _to_birthdata(req)
    chart = _safe_compute(birth)
    dashas = compute_vimshottari(chart, include_pratyantar=False)
    yogas = detect_all_yogas(chart)

    section_ids = req.sections if req.sections else _all_section_ids()

    try:
        engine = NarrativeEngine()
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"LLM provider unavailable: {e}",
        )

    options = NarrativeOptions(
        language=req.language,
        sections=section_ids,
        model=req.model,
        temperature=req.temperature,
        use_response_cache=req.use_response_cache,
        parallel=req.parallel,
    )

    try:
        result = engine.generate(chart, yogas, dashas, options)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"LLM generation failed: {e}",
        )

    section_models = [
        NarrativeSectionResponse(
            section=sid,
            title=SECTION_HEADERS[sid],
            text=result.sections.get(sid, ""),
        )
        for sid in section_ids
        if sid in result.sections
    ]

    return NarrativeResponse(
        language=req.language,
        model=req.model,
        provider=result.provider_name,
        sections=section_models,
        markdown=result.to_markdown(include_digest=req.include_digest_in_response),
        digest=result.digest if req.include_digest_in_response else None,
        disclaimer=DISCLAIMER,
        usage={
            "response_cache_hit":   result.usage.response_cache_hit,
            "total_input_tokens":   result.usage.total_input,
            "total_output_tokens":  result.usage.total_output,
            "cache_read_tokens":    result.usage.total_cache_read,
            "cache_write_tokens":   result.usage.total_cache_write,
            "prompt_cache_hits":    sum(1 for s in result.usage.sections if s.cache_hit),
            "sections_generated":   len(result.usage.sections),
        },
    )
