"""
Horoscope Agent — orchestrates chart, dasha, yoga, and interpretation
modules to produce a full Kerala-style janma-kundali report.
"""

from datetime import datetime
from typing import List, Dict

from ..core.chart import BirthData, compute_chart, format_chart_summary, Chart
from ..core.dasha import (compute_vimshottari, format_dasha_table,
                          find_current_dasha, find_current_antardasha,
                          DashaPeriod)
from ..core.yogas import detect_all_yogas, format_yogas, Yoga
from ..core.interpret import interpret_mahadasha, interpret_antardasha
from ..core.constants import (NAKSHATRA_GANAM, NAKSHATRA_NADI,
                              BHAVA_MEANINGS, RASI_LORDS, NATURAL_KARAKAS)


class HoroscopeAgent:
    """Top-level agent. Single entry point: `generate(birth_data)`."""

    def __init__(self, include_pratyantar: bool = False):
        self.include_pratyantar = include_pratyantar

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def generate(self, birth: BirthData) -> Dict:
        """Compute everything and return a structured dict + text report."""
        chart = compute_chart(birth)
        dashas = compute_vimshottari(chart,
                                     include_pratyantar=self.include_pratyantar)
        yogas = detect_all_yogas(chart)
        current_md = find_current_dasha(dashas)
        current_ad = (find_current_antardasha(current_md)
                      if current_md else None)

        report_text = self._render_report(chart, dashas, yogas,
                                          current_md, current_ad)
        return {
            "chart": chart,
            "dashas": dashas,
            "yogas": yogas,
            "current_mahadasha": current_md,
            "current_antardasha": current_ad,
            "report_text": report_text,
        }

    # ------------------------------------------------------------------
    # Report rendering
    # ------------------------------------------------------------------
    def _render_report(self, chart: Chart, dashas: List[DashaPeriod],
                       yogas: List[Yoga],
                       current_md: DashaPeriod,
                       current_ad: DashaPeriod) -> str:
        s = []
        s.append("═" * 78)
        s.append(f"  ROOM 48 — JANMA KUNDALI — {chart.birth.name}")
        s.append(f"  (Kerala Parashari tradition · Lahiri ayanamsa)")
        s.append("═" * 78)

        # 1. Janma Vivaram
        s.append("\n\n§1. JANMA VIVARAM")
        s.append("-" * 78)
        s.append(format_chart_summary(chart))

        # Nakshatra details
        moon = chart.planets["Moon"]
        s.append("\n")
        s.append(f"Janma Nakshatra : {moon.nakshatra} (pada {moon.pada})")
        s.append(f"Janma Rasi      : {moon.rasi_name}")
        s.append(f"Ganam           : {NAKSHATRA_GANAM[moon.nakshatra]}")
        s.append(f"Nadi            : {NAKSHATRA_NADI[moon.nakshatra]}")
        s.append(f"Nakshatra Lord  : {moon.nakshatra_lord}")

        # 2. Vyakti Swabhavam — basic personality
        s.append("\n\n§2. VYAKTI SWABHAVAM (PERSONALITY)")
        s.append("-" * 78)
        s.append(self._personality_paragraph(chart))

        # 3. Bhava Phalam — house analysis snapshot
        s.append("\n\n§3. BHAVA PHALAM (HOUSE ANALYSIS)")
        s.append("-" * 78)
        s.append(self._bhava_summary(chart))

        # 4. Yogas
        s.append("\n\n§4. YOGA PHALAM")
        s.append("-" * 78)
        s.append(format_yogas(yogas))

        # 5. Dasha overview
        s.append("\n\n§5. VIMSHOTTARI DASHA — OVERVIEW")
        s.append("-" * 78)
        s.append(format_dasha_table(dashas, show_antar=False))

        # 6. Current period detail
        s.append("\n\n§6. CURRENT PERIOD — DASHA PHALAM")
        s.append("-" * 78)
        if current_md:
            s.append(interpret_mahadasha(chart, current_md))
            if current_ad:
                s.append("\n→ " + interpret_antardasha(chart, current_md, current_ad))
        else:
            s.append("Outside the calculated 120-year window.")

        # 7. Upcoming Mahadashas — brief
        s.append("\n\n§7. UPCOMING MAHADASHAS — KEY THEMES")
        s.append("-" * 78)
        now = datetime.utcnow()
        upcoming = [md for md in dashas if md.start > now][:3]
        for md in upcoming:
            s.append("\n" + interpret_mahadasha(chart, md))
            s.append("")

        # 8. Disclaimer
        s.append("\n\n§8. NOTE")
        s.append("-" * 78)
        s.append(
            "This reading is generated by a software system based on classical "
            "rules from Brihat Parashara Hora Shastra, Phaladeepika, and Kerala "
            "tradition. It indicates tendencies and karmic themes — not fixed "
            "outcomes. The Kerala tradition itself emphasises that conscious "
            "effort (purushartha) and parihara (remedial measures) can modify "
            "results. For major life decisions, consult a qualified human "
            "astrologer who can interpret subtleties this system may miss."
        )
        s.append("═" * 78)
        return "\n".join(s)

    # ------------------------------------------------------------------
    # Sub-sections
    # ------------------------------------------------------------------
    def _personality_paragraph(self, chart: Chart) -> str:
        lagna_lord = RASI_LORDS[chart.lagna_rasi_index]
        ll_planet = chart.planets[lagna_lord]
        moon = chart.planets["Moon"]
        sun = chart.planets["Sun"]

        text = []
        text.append(
            f"The Lagna is {chart.lagna_rasi_name}, ruled by {lagna_lord}. "
            f"The Lagna lord is placed in house {ll_planet.house} "
            f"({BHAVA_MEANINGS[ll_planet.house]}), in {ll_planet.rasi_name}"
            + (f" — {ll_planet.dignity.lower()}." if ll_planet.dignity else ".")
        )
        text.append(
            f"\nThe Moon in {moon.rasi_name} (nakshatra {moon.nakshatra}) "
            f"colours the emotional nature: ganam is "
            f"{NAKSHATRA_GANAM[moon.nakshatra]}, nadi is "
            f"{NAKSHATRA_NADI[moon.nakshatra]}."
        )
        text.append(
            f"\nThe Sun in {sun.rasi_name} (house {sun.house}) reflects the "
            f"core identity and vitality."
        )

        # Ganam descriptors
        ganam_desc = {
            "Deva":     "natural inclination toward dharmic, refined and harmonious behaviour",
            "Manushya": "balanced human qualities — practical, sociable, ambitious",
            "Rakshasa": "intense, willful temperament; strong-minded, sometimes unconventional",
        }
        text.append(
            f"\nThe {NAKSHATRA_GANAM[moon.nakshatra]} ganam suggests "
            f"{ganam_desc[NAKSHATRA_GANAM[moon.nakshatra]]}."
        )
        return " ".join(text)

    def _bhava_summary(self, chart: Chart) -> str:
        lines = []
        for h in range(1, 13):
            occupants = chart.planet_in_house(h)
            lord = RASI_LORDS[(chart.lagna_rasi_index + h - 1) % 12]
            lord_place = chart.planets[lord].house
            meaning = BHAVA_MEANINGS[h]
            occ_text = (", ".join(occupants) if occupants else "—")
            lines.append(
                f"H{h:>2} {meaning[:50]:<50}  "
                f"Lord:{lord:<8} (in H{lord_place})  "
                f"Occupants: {occ_text}"
            )
        return "\n".join(lines)
